dist: trusty
sudo: required
language: go

go:
  - 1.10.x

matrix:
  allow_failures:
    - go: master

env:
  - MONGODB_IMAGE=mongo:3.2
  - MONGODB_IMAGE=mongo:3.4
  - MONGODB_IMAGE=mongo:3.6
  - MONGODB_IMAGE=percona/percona-server-mongodb:3.2
  - MONGODB_IMAGE=percona/percona-server-mongodb:3.4
  - MONGODB_IMAGE=percona/percona-server-mongodb:3.6

services:
  - docker

before_script:
  # Start docker containers.
  - docker-compose up -d
  # Wait for MongoDB to become available.
  - |
    until docker-compose exec mongo mongo --quiet --eval 'db.runCommand("ping").ok' > /dev/null; do
      >&2 echo "MongoDB is unavailable - sleeping"
      sleep 1
    done
    >&2 echo "MongoDB is up"
  # Display logs for debug purposes.
  - docker-compose logs
  # Display versions.
  - docker --version
  - docker-compose --version
  - docker-compose exec mongo mongo --version

script:
  # ensure that vendor/ is in sync with code and Gopkg.*
  - curl https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 -L -o ~/dep && chmod +x ~/dep
  - rm -fr vendor/
  - ~/dep ensure -v
  - git diff --exit-code

  - make format build testall

after_success:
  - bash <(curl -s https://codecov.io/bash) -X fix
